# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backendshui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backendshui

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
  httpApi:
    cors: true

functions:
  GetAllPosts:
    handler: functions/GetAllPosts/index.handler
    events:
      - httpApi:
          path: /api/posts
          method: get

  GetPostsFromUsername:
    handler: functions/GetPostsFromUsername/index.handler
    events:
      - httpApi:
          path: /api/{username}
          method: get

  PostMessage:
    handler: functions/PostMessage/index.handler
    events:
      - httpApi:
          path: /api/post
          method: post

  ChangePost:
    handler: functions/ChangePost/index.handler
    events:
      - httpApi:
          path: /api/post
          method: put

  DeletePost:
    handler: functions/DeletePost/index.handler
    events:
      - httpApi:
          path: /api/post/{id}
          method: delete

resources:
  Resources:
    ShuiBillboardTable: # Första tabellen
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "Shui-billboard-db" # Namnet på din tabell
        AttributeDefinitions:
          - AttributeName: "postId" # Definiera attribut för din partition key
            AttributeType: "S" # S för sträng
        KeySchema:
          - AttributeName: "postId" # Partition key
            KeyType: HASH # Detta är din PK (Partition Key)
        BillingMode: PAY_PER_REQUEST # Betalning per användning
